---
name: 🎶 Add a song
about: Add a new song to the list.
title: '[SONG] <title>'
labels: Bug, Needs Triage
assignees: ''

---

### Checks before adding a new music:
<!--
Example: Checks before adding a music:
1. [] Add the music file in the 'music' folder
2. [] Add the album image into the 'img' folder
3. [] Add the following details 
```
{
   title: 'Music Name',
   artist: 'Artist Name',
   song_path: 'music/music_name.mp3',
   image_path: 'img/album_image_name.jpg'
}
```
-->

### Thank You:
<!--
Thank You for your contribution! 
-->
