name: New Feature
description: Use this template for tracking new features
title: "[DATE]: <FEATURE NAME>"
labels: [enhancement]
body:
- type: checkboxes
  attributes:
   label: Is there an existing issue for this?
   description: Please search to see if an issue already exists for the bug you encountered.
   options:
   - label: I have searched for the existing issues
     required: true
- type: textarea
  attributes:
   label: Current Behavior
   description: Describe what you are experiencing.
  validations:
   required: false
- type: textarea
  attributes:
   label: Expected Behavior
   description: Describe what you expect to happen.
  validations: 
   required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: false
- type: textarea
  attributes:
   label: Anything else to add?
   description: Links? References? Anything that will give us more context about the issue you are encountering!
   Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
   required: false

